[package]
name = "rust_book_examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
    "guessing_game",
    "minigrep",
    "serv"
]


[dependencies]
rand = "0.8.3"